---
title: "Regression workflow and documentation"
output: rmarkdown::html_vignette
author: "keaton@virgalabs.io"
date: 2023-01-19
vignette: >
  %\VignetteIndexEntry{regression_example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Generally this workflow is designed to outline and document building predictive regression models to convert live storage from the BoR Hydrodata API to pool elevations for both Lake Mead and Lake Powell

These models will be used in the Colorado River Tracker to generate projected elevation levels based on projected storage volumes
```{r setup}
devtools::load_all(pkgload::pkg_path())
```
```{r}
# get data
powell_elev_data = get_res_data(919, 49)
powell_storage_data = get_res_data(919, 17)
mead_elev_data = get_res_data(921, 49)
mead_storage_data = get_res_data(921, 17)

# combine
powell = dplyr::left_join(powell_elev_data, powell_storage_data) |> dplyr::rename(pool_elevation = `pool elevation`)
mead = dplyr::left_join(mead_elev_data, mead_storage_data) |> dplyr::rename(pool_elevation = `pool elevation`)

# powell graph
powell |>
  ggplot2::ggplot(ggplot2::aes(x = storage, y = pool_elevation)) +
  ggplot2::geom_point()

# mead graph
mead |>
  ggplot2::ggplot(ggplot2::aes(x = storage, y = pool_elevation)) +
  ggplot2::geom_point()

# model polynomial
powell_mod = stats::lm(pool_elevation ~ stats::poly(storage, 2), data = powell)
mead_mod = stats::lm(pool_elevation ~ stats::poly(storage,2), data = mead |> tidyr::drop_na())

# summaries - pretty good on both
summary(powell_mod)
summary(mead_mod)
broom::tidy(powell_mod)
broom::glance(powell_mod)

```

