.dam_opts <-
c(`Agate Dam` = "/projects/index.php?id=20", `Agency Valley Dam` = "/projects/index.php?id=261", 
`Alcova Dam` = "/projects/index.php?id=21", `Almena Diversion Dam` = "/projects/index.php?id=22", 
`Altus Dam` = "/projects/index.php?id=23", `American Diversion Dam` = "/projects/index.php?id=263", 
`American Falls Dam` = "/projects/index.php?id=24", `Anchor Dam` = "/projects/index.php?id=25", 
`Anderson Ranch Dam` = "/projects/index.php?id=259", `Anderson-Rose Diversion Dam` = "/projects/index.php?id=2", 
`Angostura Dam` = "/projects/index.php?id=4", `Angostura Diversion Dam` = "/projects/index.php?id=3", 
`Anita Dam` = "/projects/index.php?id=5", `Arbuckle Dam` = "/projects/index.php?id=269", 
`Arrowrock Dam` = "/projects/index.php?id=6", `Arthur R Bowman Dam` = "/projects/index.php?id=45", 
`Arthur V Watkins Dam` = "/projects/index.php?id=48", `Avalon Dam` = "/projects/index.php?id=49", 
`B F Sisk Dam` = "/projects/index.php?id=57", `Barretts Diversion Dam` = "/projects/index.php?id=271", 
`Bartlett Dam` = "/projects/index.php?id=51", `Bartley Diversion Dam` = "/projects/index.php?id=54", 
`Belle Fourche Dam` = "/projects/index.php?id=71", `Belle Fourche Diversion Dam` = "/projects/index.php?id=56", 
`Big Sandy Dam` = "/projects/index.php?id=272", `Black Canyon Diversion Dam` = "/projects/index.php?id=7", 
`Blue Mesa Dam` = "/projects/index.php?id=62", `Boca Dam` = "/projects/index.php?id=64", 
`Boise River Diversion Dam` = "/projects/index.php?id=8", `Bonny Dam` = "/projects/index.php?id=66", 
`Box Butte Dam` = "/projects/index.php?id=67", `Boysen Dam` = "/projects/index.php?id=26", 
`Bradbury Dam` = "/projects/index.php?id=254", `Brantley Dam` = "/projects/index.php?id=28", 
`Bretch Diversion Dam` = "/projects/index.php?id=273", `Broadhead Diversion Dam` = "/projects/index.php?id=274", 
`Buckhorn Dam` = "/projects/index.php?id=31", `Buffalo Bill Dam` = "/projects/index.php?id=33", 
`Bull Lake Dam` = "/projects/index.php?id=36", `Bully Creek Dam` = "/projects/index.php?id=37", 
`Bumping Lake Dam` = "/projects/index.php?id=40", `C.C. Cragin` = "/projects/index.php?id=1", 
`Caballo Dam` = "/projects/index.php?id=42", `Cambridge Diversion Dam` = "/projects/index.php?id=43", 
`Camp Creek Diversion Dam` = "/projects/index.php?id=275", `Camp Dyer Diversion Dam` = "/projects/index.php?id=46", 
`Canyon Ferry Dam` = "/projects/index.php?id=50", `Carpinteria Dam` = "/projects/index.php?id=9", 
`Carson River Diversion Dam` = "/projects/index.php?id=52", `Carter Creek Diversion Dam` = "/projects/index.php?id=53", 
`Carter Lake Dam` = "/projects/index.php?id=55", `Cascade Dam` = "/projects/index.php?id=10", 
`Casitas Dam` = "/projects/index.php?id=276", `Causey Dam` = "/projects/index.php?id=58", 
`Cedar Bluff Dam` = "/projects/index.php?id=59", `Chapman Diversion Dam` = "/projects/index.php?id=60", 
`Cheney Dam` = "/projects/index.php?id=63", `Choke Canyon Dam` = "/projects/index.php?id=65", 
`Clark Canyon Dam` = "/projects/index.php?id=68", `Cle Elum Dam` = "/projects/index.php?id=306", 
`Clear Creek Dam` = "/projects/index.php?id=69", `Clear Lake Dam` = "/projects/index.php?id=27", 
`Cold Springs Dam` = "/projects/index.php?id=29", `Como Dam` = "/projects/index.php?id=30", 
`Conconully Dam` = "/projects/index.php?id=32", `Contra Loma Dam` = "/projects/index.php?id=34", 
`Corbett Diversion Dam` = "/projects/index.php?id=35", `Crane Prairie Dam` = "/projects/index.php?id=38", 
`Crawford Dam` = "/projects/index.php?id=39", `Crystal Dam` = "/projects/index.php?id=41", 
`Culbertson Diversion Dam` = "/projects/index.php?id=277", `Currant Creek Dam` = "/projects/index.php?id=44", 
`Davis Creek Dam` = "/projects/index.php?id=70", `Davis Dam` = "/projects/index.php?id=47", 
`Deadwood Dam` = "/projects/index.php?id=11", `Deaver Dam` = "/projects/index.php?id=75", 
`Deer Creek Dam` = "/projects/index.php?id=76", `Deer Flat Lower Embankment` = "/projects/index.php?id=13", 
`Deer Flat Middle Embankment` = "/projects/index.php?id=14", 
`Deer Flat Upper Embankment` = "/projects/index.php?id=15", `Deerfield Dam` = "/projects/index.php?id=100", 
`Derby Diversion Dam` = "/projects/index.php?id=77", `Dickinson Dam` = "/projects/index.php?id=78", 
`Dille Diversion Dam` = "/projects/index.php?id=61", `Dixon Canyon Dam` = "/projects/index.php?id=79", 
`Dodson Diversion Dam` = "/projects/index.php?id=80", `Dressler Diversion Dam` = "/projects/index.php?id=81", 
`Dry Creek Diversion Dam` = "/projects/index.php?id=82", `Dry Falls Dam` = "/projects/index.php?id=84", 
`Dry Spotted Tail Diversion Dam` = "/projects/index.php?id=285", 
`Dunlap Diversion Dam` = "/projects/index.php?id=286", `East Canyon Dam` = "/projects/index.php?id=88", 
`East Park Dam` = "/projects/index.php?id=89", `East Portal Diversion Dam` = "/projects/index.php?id=287", 
`Easton Diversion Dam` = "/projects/index.php?id=103", `Echo Dam` = "/projects/index.php?id=92", 
`Eden Dam` = "/projects/index.php?id=93", `El Vado Dam` = "/projects/index.php?id=96", 
`Elephant Butte Dam` = "/projects/index.php?id=94", `Emigrant Dam` = "/projects/index.php?id=97", 
`Enders Dam` = "/projects/index.php?id=99", `Fish Lake Dam` = "/projects/index.php?id=104", 
`Flaming Gorge Dam` = "/projects/index.php?id=105", `Flatiron Afterbay Dam` = "/projects/index.php?id=72", 
`Folsom Dam` = "/projects/index.php?id=74", `Fontenelle Dam` = "/projects/index.php?id=288", 
`Fort Cobb Dam` = "/projects/index.php?id=289", `Fort Shaw Diversion Dam and Canal` = "/projects/index.php?id=117", 
`Foss Dam` = "/projects/index.php?id=121", `French Canyon Dam` = "/projects/index.php?id=127", 
`Fresno Dam` = "/projects/index.php?id=128", `Friant Dam` = "/projects/index.php?id=133", 
`Fruitgrowers Dam` = "/projects/index.php?id=138", `Fryingpan Diversion Dam` = "/projects/index.php?id=296", 
`Funks Dam` = "/projects/index.php?id=139", `Garnet Diversion Dam` = "/projects/index.php?id=283", 
`Gerber Dam` = "/projects/index.php?id=73", `Gibson Dam` = "/projects/index.php?id=284", 
`Glen Anne Dam` = "/projects/index.php?id=16", `Glen Canyon Dam` = "/projects/index.php?id=144", 
`Glen Elder Dam` = "/projects/index.php?id=149", `Glendo Dam` = "/projects/index.php?id=290", 
`Granby Dam` = "/projects/index.php?id=291", `Grand Coulee Dam` = "/projects/index.php?id=155", 
`Granite Creek Diversion Dam` = "/projects/index.php?id=161", 
`Granite Reef Diversion Dam` = "/projects/index.php?id=165", 
`Grassy Lake Dam` = "/projects/index.php?id=166", `Gray Reef Dam` = "/projects/index.php?id=292", 
`Green Mountain Dam` = "/projects/index.php?id=174", `Guernsey Dam` = "/projects/index.php?id=175", 
`Halfmoon Diversion Dam` = "/projects/index.php?id=179", `Haystack Dam` = "/projects/index.php?id=183", 
`Heart Butte Dam` = "/projects/index.php?id=112", `Helena Valley Dam` = "/projects/index.php?id=113", 
`Heron Dam` = "/projects/index.php?id=118", `Hoover Dam` = "/projects/index.php?id=122", 
`Horse Creek Diversion Dam` = "/projects/index.php?id=123", `Horse Mesa Dam` = "/projects/index.php?id=129", 
`Horseshoe Dam` = "/projects/index.php?id=134", `Horsetooth Dam` = "/projects/index.php?id=119", 
`Howard Prairie Dam` = "/projects/index.php?id=124", `Hubbard Dam` = "/projects/index.php?id=17", 
`Hungry Horse Dam` = "/projects/index.php?id=255", `Hunter Creek Diversion Dam` = "/projects/index.php?id=293", 
`Huntington North Dam` = "/projects/index.php?id=140", `Hyatt Dam` = "/projects/index.php?id=141", 
`Hyrum Dam` = "/projects/index.php?id=145", `Imperial Diversion Dam` = "/projects/index.php?id=150", 
`Island Park Dam` = "/projects/index.php?id=151", `Isleta Diversion Dam` = "/projects/index.php?id=130", 
`Ivanhoe Diversion Dam` = "/projects/index.php?id=131", `Jackson Gulch Dam` = "/projects/index.php?id=156", 
`Jackson Lake Dam` = "/projects/index.php?id=162", `James Diversion Dam` = "/projects/index.php?id=157", 
`Jamestown Dam` = "/projects/index.php?id=167", `Joes Valley Dam` = "/projects/index.php?id=168", 
`John Franchi Diversion Dam` = "/projects/index.php?id=171", 
`Jordanelle Dam` = "/projects/index.php?id=176", `Kachess Dam` = "/projects/index.php?id=135", 
`Keechelus Dam` = "/projects/index.php?id=294", `Keene Creek Dam` = "/projects/index.php?id=295", 
`Kent Diversion Dam` = "/projects/index.php?id=184", `Keswick Dam` = "/projects/index.php?id=185", 
`Keyhole Dam` = "/projects/index.php?id=107", `Kirwin Dam` = "/projects/index.php?id=108", 
`Kortes Dam` = "/projects/index.php?id=114", `Laguna Diversion Dam` = "/projects/index.php?id=297", 
`Lahontan Dam` = "/projects/index.php?id=142", `Lake Alice No 1 Dam` = "/projects/index.php?id=146", 
`Lake Alice No 1and 1 Half Dam` = "/projects/index.php?id=298", 
`Lake Alice No 2 Dam` = "/projects/index.php?id=152", `Lake Sherburne Dam` = "/projects/index.php?id=158", 
`Lake Tahoe Dam` = "/projects/index.php?id=159", `Lauro Dam` = "/projects/index.php?id=18", 
`Lemon Dam` = "/projects/index.php?id=163", `Lewiston Dam` = "/projects/index.php?id=169", 
`Lily Pad Diversion Inlet Dam` = "/projects/index.php?id=170", 
`Link River Diversion Dam` = "/projects/index.php?id=172", `Little Hell Creek Diversion Dam` = "/projects/index.php?id=278", 
`Little Panoche Detention Dam` = "/projects/index.php?id=279", 
`Little Wood River Dam` = "/projects/index.php?id=180", `Los Banos Creek Detention Dam` = "/projects/index.php?id=280", 
`Lost Creek Dam` = "/projects/index.php?id=109", `Lost River Diversion Dam` = "/projects/index.php?id=115", 
`Lovewell Dam` = "/projects/index.php?id=116", `Lower Yellowstone Diversion Dam` = "/projects/index.php?id=120", 
`Malone Diversion Dam` = "/projects/index.php?id=125", `Mann Creek Dam` = "/projects/index.php?id=126", 
`Marble Bluff Dam` = "/projects/index.php?id=132", `Martinez Dam` = "/projects/index.php?id=136", 
`Marys Lake Dike Dam` = "/projects/index.php?id=137", `Mason Dam` = "/projects/index.php?id=143", 
`McGee Creek Dam` = "/projects/index.php?id=147", `McKay Dam` = "/projects/index.php?id=148", 
`McPhee Dam` = "/projects/index.php?id=153", `Medicine Creek Dam` = "/projects/index.php?id=154", 
`Meeks Cabin Dam` = "/projects/index.php?id=160", `Merritt Dam` = "/projects/index.php?id=164", 
`Middle Cunningham Creek Diversion Dam` = "/projects/index.php?id=303", 
`Midview Dam` = "/projects/index.php?id=304", `Midway Creek Diversion Dam` = "/projects/index.php?id=173", 
`Miller Diversion Dam` = "/projects/index.php?id=177", `Minatare Dam` = "/projects/index.php?id=178", 
`Minidoka Dam` = "/projects/index.php?id=181", `Monticello Dam` = "/projects/index.php?id=186", 
`Moon Lake Dam` = "/projects/index.php?id=187", `Mormon Creek Diversion Dam` = "/projects/index.php?id=106", 
`Mormon Flat Dam` = "/projects/index.php?id=110", `Mormon Island Auxilliary Dam` = "/projects/index.php?id=111", 
`Morrow Point Dam` = "/projects/index.php?id=197", `Mountain Park Dam` = "/projects/index.php?id=200", 
`Mt Elbert Forebay Dam` = "/projects/index.php?id=308", `Nambe Falls Dam` = "/projects/index.php?id=309", 
`Navajo Dam` = "/projects/index.php?id=310", `Nelson Dam` = "/projects/index.php?id=206", 
`New Melones Dam` = "/projects/index.php?id=211", `New Waddell Dam` = "/projects/index.php?id=311", 
`Newton Dam` = "/projects/index.php?id=217", `Nimbus Dam` = "/projects/index.php?id=222", 
`No Name Creek Diversion Dam` = "/projects/index.php?id=223", 
`Norman Dam` = "/projects/index.php?id=227", `North Cunningham Creek Diversion Dam` = "/projects/index.php?id=312", 
`North Dam` = "/projects/index.php?id=228", `North Fork Diversion Dam` = "/projects/index.php?id=313", 
`Northside Diversion Dam` = "/projects/index.php?id=237", `Norton Dam` = "/projects/index.php?id=238", 
`Ochoco Dam` = "/projects/index.php?id=248", `Olympus Dam` = "/projects/index.php?id=249", 
`Ortega Dam` = "/projects/index.php?id=19", `Owyhee Dam` = "/projects/index.php?id=315", 
`O'Neill Dam` = "/projects/index.php?id=314", `O'Sullivan Dam` = "/projects/index.php?id=194", 
`Pactola Dam` = "/projects/index.php?id=316", `Palisades Dam` = "/projects/index.php?id=317", 
`Palo Verde Diversion Dam` = "/projects/index.php?id=201", `Paonia Dam` = "/projects/index.php?id=203", 
`Paradise Diversion Dam` = "/projects/index.php?id=204", `Parker Dam` = "/projects/index.php?id=207", 
`Pathfinder Dam` = "/projects/index.php?id=212", `Pathfinder Dike Dam` = "/projects/index.php?id=213", 
`Pilot Butte Dam` = "/projects/index.php?id=318", `Pineview Dam` = "/projects/index.php?id=218", 
`Pinto Dam` = "/projects/index.php?id=219", `Pishkun Dikes` = "/projects/index.php?id=319", 
`Platoro Dam` = "/projects/index.php?id=224", `Pole Hill Afterbay Dam` = "/projects/index.php?id=229", 
`Prosser Creek Dam` = "/projects/index.php?id=320", `Pueblo Dam` = "/projects/index.php?id=232", 
`Putah Dam` = "/projects/index.php?id=234", `Rainbow Diversion Dam` = "/projects/index.php?id=239", 
`Ralston Dam` = "/projects/index.php?id=240", `Rattlesnake Dam` = "/projects/index.php?id=243", 
`Red Bluff Diversion Dam` = "/projects/index.php?id=244", `Red Fleet Dam` = "/projects/index.php?id=250", 
`Red Willow Creek Diversion Dam` = "/projects/index.php?id=189", 
`Red Willow Dam` = "/projects/index.php?id=321", `Reservoir A Dam` = "/projects/index.php?id=267", 
`Ridges Basin Dam` = "/projects/index.php?id=581", `Ridgway Dam` = "/projects/index.php?id=195", 
`Rifle Gap Dam` = "/projects/index.php?id=198", `Ririe Dam` = "/projects/index.php?id=199", 
`Robles Dam` = "/projects/index.php?id=322", `Roza Diversion Dam` = "/projects/index.php?id=323", 
`Ruedi Dam` = "/projects/index.php?id=208", `Rye Patch Dam` = "/projects/index.php?id=268", 
`Salmon Lake Dam` = "/projects/index.php?id=214", `San Acacia Diversion Dam` = "/projects/index.php?id=324", 
`San Justo Dam` = "/projects/index.php?id=325", `Sanford Dam` = "/projects/index.php?id=270", 
`Satanka Dike Dam` = "/projects/index.php?id=220", `Sawyer Diversion Dam` = "/projects/index.php?id=326", 
`Scofield Dam` = "/projects/index.php?id=327", `Scoggins Dam` = "/projects/index.php?id=225", 
`Seminoe Dam` = "/projects/index.php?id=233", `Senator Wash Dam` = "/projects/index.php?id=328", 
`Shadehill Dam` = "/projects/index.php?id=329", `Shadow Mountain Dam` = "/projects/index.php?id=235", 
`Shasta Dam` = "/projects/index.php?id=241", `Silver Jack Dam` = "/projects/index.php?id=245", 
`Sly Park Dam` = "/projects/index.php?id=246", `Soldier Canyon Dam` = "/projects/index.php?id=251", 
`Soldier Creek Dam` = "/projects/index.php?id=190", `Soldiers Meadow Dam` = "/projects/index.php?id=191", 
`South Cunningham Creek Diversion Dam` = "/projects/index.php?id=196", 
`South Fork Diversion Dam` = "/projects/index.php?id=330", `Spring Canyon Dam` = "/projects/index.php?id=331", 
`Spring Creek Debris Dam` = "/projects/index.php?id=202", `St. Mary Diversion Dam` = "/projects/index.php?id=332", 
`Stampede Dam` = "/projects/index.php?id=205", `Starvation Dam` = "/projects/index.php?id=209", 
`Stateline Dam` = "/projects/index.php?id=210", `Steinaker Dam` = "/projects/index.php?id=215", 
`Stewart Mountain Dam` = "/projects/index.php?id=216", `Stony Gorge Dam` = "/projects/index.php?id=333", 
`Sugar Loaf Dam` = "/projects/index.php?id=221", `Sumner Dam` = "/projects/index.php?id=226", 
`Sun River Diversion Dam` = "/projects/index.php?id=230", `Superior Courtland Diversion Dam` = "/projects/index.php?id=231", 
`Swift Current Dike` = "/projects/index.php?id=334", `Taylor Park Dam` = "/projects/index.php?id=236", 
`Terminal Dam` = "/projects/index.php?id=299", `Theodore Roosevelt Dam` = "/projects/index.php?id=242", 
`Thief Valley Dam` = "/projects/index.php?id=300", `Three Mile Falls Diversion Dam` = "/projects/index.php?id=247", 
`Tiber Dam` = "/projects/index.php?id=252", `Tieton Dam` = "/projects/index.php?id=253", 
`Trenton Dam` = "/projects/index.php?id=188", `Trinity Dam` = "/projects/index.php?id=266", 
`Tub Springs Creek Diversion Dam` = "/projects/index.php?id=192", 
`Twin Buttes Dam` = "/projects/index.php?id=307", `Twin Lakes Dam` = "/projects/index.php?id=305", 
`Twitchell Dam` = "/projects/index.php?id=193", `Unity Dam` = "/projects/index.php?id=256", 
`Upper Slaven Diversion Dam` = "/projects/index.php?id=301", 
`Upper Stillwater Dam` = "/projects/index.php?id=257", `Vallecito Dam` = "/projects/index.php?id=258", 
`Vandalia Diversion Dam` = "/projects/index.php?id=335", `Vega Dam` = "/projects/index.php?id=260", 
`Virginia Smith Dam` = "/projects/index.php?id=302", `Wanship Dam` = "/projects/index.php?id=83", 
`Warm Springs Dam` = "/projects/index.php?id=85", `Wasco Dam` = "/projects/index.php?id=86", 
`Webster Dam` = "/projects/index.php?id=281", `Whalen Diversion Dam` = "/projects/index.php?id=87", 
`Whiskeytown Dam` = "/projects/index.php?id=90", `Wickiup Dam` = "/projects/index.php?id=91", 
`Willow Creek Co Dam` = "/projects/index.php?id=98", `Willow Creek Dam` = "/projects/index.php?id=95", 
`Willwood Diversion Dam` = "/projects/index.php?id=282", `Wind River Diversion Dam` = "/projects/index.php?id=101", 
`Woodston Diversion Dam` = "/projects/index.php?id=102", `Yellowstone River Diversion Dam` = "/projects/index.php?id=262", 
`Yellowtail Afterbay Dam` = "/projects/index.php?id=265", `Yellowtail Dam` = "/projects/index.php?id=264"
)
